[tool.poetry]
name = "aws-front"
version = "0.1.0"
description = ""
authors = ["imjoo0 <im_joo0@naver.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

